apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenweb
  labels:
    type: maven
spec:
  replicas: 2
  selector:
    matchLabels:
      type: web
  template:
    metadata:
      name: web
      labels:
        type: web
    spec:
      containers:
        - name: webapp
          image: chaitanya9666/maven:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: maven
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30005
  selector:
    type: web
